import type { AgentRecord } from "./types";

// Priority rules:
//   high   = websites / customer-facing products (Grand Masters)
//   medium = SaaS replacements / business automation tools (Jedi Knights)
//   low    = personal / experimental / utility projects (fun characters)

export const MOCK_AGENTS: AgentRecord[] = [
  // ── HIGH: Websites (Grand Masters) ────────────────────────────────────────
  {
    id: "neurogan-cbd-agent",
    name: "neurogan-cbd-agent",
    source: "claude-code",
    status: "active",
    priority: "high",
    task: "AEO/GEO 2026 framework — AI-optimised content for neurogan.com & neuroganhealth.com",
    connections: ["ahrefs-user", "replacer-reb"],
    startedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "neurogan-pets-agent",
    name: "neurogan-pets-agent",
    source: "claude-code",
    status: "active",
    priority: "high",
    task: "Managing neurogan-pets.myshopify.com — syncing inventory & wholesale orders",
    connections: ["faire"],
    startedAt: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
  },
  {
    id: "doge-dashboard",
    name: "doge-cuts-dashboard",
    source: "railway",
    status: "active",
    priority: "high",
    task: "Serving live team-wins leaderboard — 3 active users connected",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "neurogan-launch-dashboard",
    name: "neurogan-launch-dashboard-next",
    source: "railway",
    status: "active",
    priority: "high",
    task: "Launch dashboard — tracking campaign KPIs for Q2 product rollout",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "ahk-cu-agent",
    name: "ahk-cu-agent",
    source: "claude-code",
    status: "idle",
    priority: "high",
    task: "AHK-CU website agent — standing by for content updates",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "stemcodewebsite",
    name: "stemcodewebsite",
    source: "local",
    status: "idle",
    priority: "high",
    task: "Stem Code website — standing by for next deployment",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },

  // ── MEDIUM: SaaS Replacements / Business Tools (Jedi Knights) ────────────
  {
    id: "replacer-reb",
    name: "replacer-reb",
    source: "railway",
    status: "active",
    priority: "medium",
    task: "Co-purchase engine replacing Rebuy — building recommendation matrix from 90-day orders",
    connections: ["neurogan-cbd-agent", "opportunity-hunter"],
    startedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "opportunity-hunter",
    name: "opportunity-hunter",
    source: "railway",
    status: "active",
    priority: "medium",
    task: "Scanning Ahrefs for top 3 buildable business opportunities across 14 niches",
    connections: ["ahrefs-user", "replacer-reb"],
    startedAt: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
  },
  {
    id: "google-ads-agent",
    name: "google-ads-agent",
    source: "claude-code",
    status: "active",
    priority: "medium",
    task: "Optimising Google Ads bid strategy — analysing ROAS across 24 ad groups",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
  },
  {
    id: "ahrefs-user",
    name: "ahrefs-user",
    source: "claude-code",
    status: "active",
    priority: "medium",
    task: "Neurogan SEO + AI-visibility program — daily crawl and AEO reporting pipeline",
    connections: ["neurogan-cbd-agent", "opportunity-hunter"],
    startedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "faire",
    name: "faire",
    source: "claude-code",
    status: "active",
    priority: "medium",
    task: "Faire wholesale API — 12 pending orders, updating inventory pricing",
    connections: ["neurogan-pets-agent"],
    startedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "refund-agent",
    name: "refund-agent",
    source: "claude-code",
    status: "error",
    priority: "medium",
    task: "Shopify refund batch — FAILED: API rate limit exceeded",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: "hermes-agent",
    name: "hermes-agent",
    source: "railway",
    status: "idle",
    priority: "medium",
    task: "Hermes comms agent — awaiting trigger event",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "fda-483",
    name: "fda-483",
    source: "claude-code",
    status: "idle",
    priority: "medium",
    task: "FDA 483 compliance monitoring — last scan completed, no new observations",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "seo-audit-loop",
    name: "seo-audit-loop",
    source: "railway",
    status: "idle",
    priority: "medium",
    task: "Weekly Ahrefs site audit — 5 Neurogan domains, next run in 4h",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "pop-pusher",
    name: "pop-pusher",
    source: "railway",
    status: "active",
    priority: "medium",
    task: "Push notification dispatcher replacing Klaviyo — 4 campaigns queued",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },

  // ── LOW: Personal / Experimental (Fun Characters) ─────────────────────────
  {
    id: "life-purpose-agent",
    name: "life-purpose-agent",
    source: "claude-code",
    status: "idle",
    priority: "low",
    task: "Life purpose reflection agent — last session 2 days ago",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "dj-sofus",
    name: "dj-sofus",
    source: "local",
    status: "idle",
    priority: "low",
    task: "DJ Sofus personal site — standing by",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "seats-watcher",
    name: "seats.aero-agent",
    source: "railway",
    status: "idle",
    priority: "low",
    task: "Award seat monitor — last checked 4 min ago, no new alerts",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "core-creatine",
    name: "core-creatine",
    source: "local",
    status: "idle",
    priority: "low",
    task: "Core creatine project — awaiting next task",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "superpowers",
    name: "superpowers",
    source: "local",
    status: "active",
    priority: "low",
    task: "Extended Claude Code skills — managing 40+ skill definitions across all sessions",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "github-agent-debug",
    name: "github-agent-debug",
    source: "claude-code",
    status: "completed",
    priority: "low",
    task: "Custom build push hooks — resolved, all 3 test pushes succeeded",
    connections: [],
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
];
